### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from 

### ISSUE THREAD

**Issue by cucy** [jethrocarr/namedmanager#27]
From root@localhost.localdomain  Mon May  2 23:59:16 2016
Return-Path: root@localhost.localdomain
X-Original-To: root
Delivered-To: root@localhost.localdomain
Received: by localhost.localdomain (Postfix, from userid 0)
        id 31F8620000AA; Mon,  2 May 2016 23:59:16 -0400 (EDT)
From: "(Cron Daemon)" root@localhost.localdomain
To: root@localhost.localdomain
Subject: Cron root@localhost php -q /usr/share/namedmanager/bind/namedmanager_bind_configwriter.php >> /var/log/namedmanager_bind_configwriter
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=72>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: 20160503035916.31F8620000AA@localhost.localdomain
Date: Mon,  2 May 2016 23:59:16 -0400 (EDT)

PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://http://10.76.249.131/namedmanager/api/namedmanager.wsdl' : failed to load external entity "http://http://10.76.249.131/namedmanager/api/namedmanager.wsdl"
 in /usr/share/namedmanager/bind/include/application/inc_soap_api.php on line 33
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://http://10.76.249.131/namedmanager/api/namedmanager.wsdl' : failed to load external entity "http://http://10.76.249.131/namedmanager/api/namedmanager.wsdl"
 in /usr/share/namedmanager/bind/include/application/inc_soap_api.php:33
Stack trace:
#0 /usr/share/namedmanager/bind/include/application/inc_soap_api.php(33): SoapClient->SoapClient('http://http://1...')
#1 /usr/share/namedmanager/bind/namedmanager_bind_configwriter.php(108): soap_api->authenticate()
#2 {main}

  thrown in /usr/share/namedmanager/bind/include/application/inc_soap_api.php on line 33

**Comment by anis-bedhiafi** [comment]
There is an extra http:// in your urls.
