### ISSUE TITLE
IPv6 reverse with PHP7

### ISSUE THREAD

**Issue by jakobkr** [jethrocarr/namedmanager#40]
There is a problem doing ip6.arpa zones with PHP7.
In htdocs/include/amberphplib/inc_security.php you are using split, which is a deprecated function.
Replacing it with the explode function, seems to do the trick.

**Comment by jethrocarr** [comment]
Please send me a PR @jakobkr and I'll be happy to merge.

**Comment by vaska94** [comment]
this should be closed, already fixed
