### ISSUE TITLE
RPM for Centos7 are not correctly (mysql-server requirement)

### ISSUE THREAD

**Issue by Priyantha** [jethrocarr/namedmanager#5]
Hi,

I had to rebuild your RPM's, I have changed the SPEC file where mysql-server is needed to mariadb-server.
After changing that en rebuilding the RPM, the RPM's installed correctly.

Think it's a good idea to change that also in your repo:)

Cheers

**Comment by frankcrawford** [comment]
In fact, I'd argue that you don't want any DB server dependency in the RPM.  Consider the trouble you would have if you have a centralised server hosted on a different machine.  You would be forcing an installation that isn't required.

**Comment by frankcrawford** [comment]
Minor second but related to CentOS 7, it also tries to run "/etc/init.d/httpd reload" during the install as well, but since RedHat have moved to systemd, it doesn't work.

It probably should be replaced with either "systemctl reload httpd.service" or just the older "service reload httpd".

**Comment by jethrocarr** [comment]
Yeah the current model of RPM isn't ideal for everyone - it's an outcome of it's requirements which was to support my managed customers with pretty much a plug & play experience with single app/db all-in-one VMs, but as pointed out, it doesn't suit the model where you have decoupled app servers and database servers.

Happy for PRs that update the dependencies and correct reloads, however I'd like to keep the coupling with the DB in the RPM for now - users running separate app vs db servers are probably better off not using the RPM package and doing manual installs from tarball or git instead.

**Comment by frankcrawford** [comment]
Not a problem.  I'll see what I can arrange.

**Comment by frankcrawford** [comment]
Okay, I've submitted a PR for you to look at and apply.  It builds fine on RHEL7 and RHEL6 (or CentOS equivalents).

Any issues, let me know.

**Comment by jethrocarr** [comment]
PR #13 looks good, thanks heaps for the submission @frankcrawford. A prebuilt RPM is now available for EL 7 at repos.jethrocarr.com for anyone wanting a pre-built version.

**Comment by frankcrawford** [comment]
@jethrocarr one issue I did notice that is still a problem with RHEL7 is that we should do a "systemctl daemon-reload" at some point during an upgrade.  I'll see what I can do about it, in a compatible way.
