### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by MACscr** [jethrocarr/namedmanager#6]
Looks like a very neat project and something I could really use. How stable is it? Any screenshots available for its interface?

**Comment by danielfaulknor** [comment]
I'm using it in production and have been for some time with no issues.

**Comment by edelans** [comment]
+I for the screenshots . I've jsut found some here : 
https://wiki.deimos.fr/NamedManager_:_une_interface_web_agr%C3%A9able_pour_administrer_Bind
